import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const data=JSON.parse(await fs.readFile(path.join(ROOT,'data/exports/excel_data.json'),'utf8'));
const out=path.join(ROOT,'excel');await fs.mkdir(out,{recursive:true});await fs.mkdir(path.join(ROOT,'docs/evidence/excel'),{recursive:true});
const wb=Workbook.create();const names=['Network','Airport','Airlines','Delay patterns','Data audit','Monthly data','Airport data','Airline data','Hour data','Read me'];
const sheets=Object.fromEntries(names.map(n=>[n,wb.worksheets.add(n)]));
const C={navy:'#10273E',ink:'#16324A',amber:'#E49B32',blue:'#2879B4',pale:'#EEF3F6',muted:'#607589',white:'#FFFFFF'};
const cols=n=>{let s='';while(n){s=String.fromCharCode(65+(n-1)%26)+s;n=Math.floor((n-1)/26);}return s;};
function val(s,c,v){s.getRange(c).values=[[v]];}
function formula(s,c,f){s.getRange(c).formulas=[[f]];}
function block(s,r,text,size=11,color=C.ink,bg=null){const a=s.getRange(r);a.merge();a.values=[[text]];a.format.font={name:'Arial',size,color};if(bg)a.format.fill=bg;}
function shell(s,title,sub){s.showGridLines=false;s.getRange('A1:P47').format={fill:C.white,font:{name:'Arial',size:11,color:C.ink},rowHeight:23,verticalAlignment:'center'};s.getRange('A1:P47').format.columnWidthPx=86;s.getRange('A1:A47').format.columnWidthPx=22;block(s,'B2:P2','FLIGHTPATH   /   U.S. AIRLINE OPERATIONS',11,C.muted);block(s,'B4:P5',title,24,C.white,C.navy);block(s,'B7:P7',sub,11,C.muted);block(s,'B9:P9','USE THE SHEET TABS:  Network    Airport    Airlines    Delay patterns    Data audit',10,C.blue);s.tabColor=C.navy;}
function table(s,at,rows,headers,name){const [row,col]=at;s.getRangeByIndexes(row-1,col-1,1,headers.length).values=[headers];s.getRangeByIndexes(row,col-1,rows.length,headers.length).values=rows;s.tables.add(`${cols(col)}${row}:${cols(col+headers.length-1)}${row+rows.length}`,true,name);s.getRangeByIndexes(row-1,col-1,1,headers.length).format={fill:C.navy,font:{name:'Arial',size:10,color:C.white,bold:true},rowHeight:30,wrapText:true};}
const numfields=['scheduled_flights','eligible_arrivals','on_time_flights','delayed_flights','cancelled_flights','severe_flights','carrier_minutes','weather_minutes','nas_minutes','security_minutes','late_aircraft_minutes'];
const rangeMap={};
for(const [name,key,dims] of [['Monthly data','monthly',['year','month']],['Airport data','airport_monthly',['year','month','origin']],['Airline data','carrier_monthly',['year','month','airline_key']],['Hour data','hourly',['year','month','departure_hour']]]){
  const s=sheets[name],fields=[...dims,...numfields];s.showGridLines=false;s.getRangeByIndexes(0,0,data[key].length+5,fields.length).format={font:{name:'Arial',size:10,color:C.ink},rowHeight:20,columnWidth:17};
  val(s,'A1','BTS monthly releases. Additive counts and minutes. Rates are calculated in the reader views.');val(s,'A2','Source: https://www.transtats.bts.gov/Fields.asp?gnoyr_VQ=FGJ');
  const rows=data[key].map(r=>fields.map(f=>r[f]??null));table(s,[4,1],rows,fields.map(f=>f.replaceAll('_',' ')),key+'Source');s.freezePanes.freezeRows(4);s.getRangeByIndexes(4,dims.length,rows.length,numfields.length).setNumberFormat('#,##0');
  rangeMap[name]=Object.fromEntries(fields.map((f,i)=>[f,`'${name}'!$${cols(i+1)}$5:$${cols(i+1)}$${rows.length+4}`]));
}
const year="'Network'!$D$12";
function sum(name,field,extra=[]){const m=rangeMap[name];return `SUMIFS(${m[field]},${m.year},${year},${m.month},"<=6"${extra.map(([f,v])=>','+m[f]+','+v).join('')})`;}
function percent(s,cell,n,d){formula(s,cell,`=IF(${d}=0,"n.a.",${n}/${d})`);s.getRange(cell).setNumberFormat('0.0%');}
function chart(s,type,ranges,title,start,end,percentAxis=true){const ch=s.charts.add(type,ranges.map(r=>s.getRange(r)));ch.title=title;ch.titleTextStyle.typeface='Arial';ch.titleTextStyle.fontSize=14;ch.hasLegend=ranges.length>2;ch.legend={position:'top',textStyle:{typeface:'Arial',fontSize:11}};ch.xAxis={axisType:'textAxis',textStyle:{typeface:'Arial',fontSize:10}};ch.yAxis={numberFormatCode:percentAxis?'0%':'#,##0',numberFormatSourceLinked:false,textStyle:{typeface:'Arial',fontSize:10}};ch.series.items.forEach((series,i)=>{const color=[C.blue,C.amber,C.muted][i%3];series.fill=color;series.line={fill:color,style:'solid',width:2};});ch.setPosition(start,end);return ch;}
// One shared selection. Equal January-June windows keep incomplete 2026 comparable.
const net=sheets.Network;shell(net,'How reliably does America fly?','January–June comparisons across 2023–2026. Change the amber year cell to update the analysis.');
val(net,'B12','Year');val(net,'D12',2026);net.getRange('D12').dataValidation={rule:{type:'list',values:['2023','2024','2025','2026']}};net.getRange('D12').format={fill:'#FFF0D7',font:{name:'Arial',size:13,bold:true,color:C.ink}};block(net,'F12:O12','PERIOD: JANUARY–JUNE   /   Amber cells are editable',10,C.muted);
const metrics=[['SCHEDULED FLIGHTS','scheduled_flights',null],['ON-TIME ARRIVALS','on_time_flights','eligible_arrivals'],['CANCELLED','cancelled_flights','scheduled_flights'],['DELAYED 60+ MIN','severe_flights','eligible_arrivals']];
metrics.forEach(([label,n,d],i)=>{const c=2+i*4;block(net,`${cols(c)}15:${cols(Math.min(c+2,16))}15`,label,10,C.muted);const addr=`${cols(c)}17`;const merged=net.getRange(`${cols(c)}17:${cols(Math.min(c+2,16))}18`);merged.merge();formula(net,addr,`=${d?sum('Monthly data',n)+'/'+sum('Monthly data',d):sum('Monthly data',n)}`);merged.setNumberFormat(d?'0.0%':'#,##0');merged.format.font={name:'Menlo',size:23,bold:true,color:C.ink};});
net.getRange('B23:F23').values=[['Month','Scheduled','Eligible arrivals','Delayed','Delay rate']];for(let m=1;m<=6;m++){const r=23+m;val(net,`B${r}`,['Jan','Feb','Mar','Apr','May','Jun'][m-1]);for(const [j,f] of [[3,'scheduled_flights'],[4,'eligible_arrivals'],[5,'delayed_flights']])formula(net,`${cols(j)}${r}`,'='+sum('Monthly data',f,[['month',String(m)]]));percent(net,`F${r}`,`E${r}`,`D${r}`);}net.getRange('C24:E29').setNumberFormat('#,##0');net.getRange('B23:F23').format={fill:C.navy,font:{color:C.white,bold:true},rowHeight:36,wrapText:true};chart(net,'line',['B23:B29','F23:F29'],'Arrival delay rate by month','H22','P38');
block(net,'B33:F34','On time means an arrival less than 15 minutes late.',11);block(net,'B36:F38','Arrival rates exclude cancellations, diversions and two missing arrival records. Cancellation rate uses scheduled flights.',10,C.muted);net.getRange('B36:F38').format.wrapText=true;
// Airport view: counts, eligibility and denominator remain visible.
const airport=sheets.Airport;shell(airport,'Airport departure board','Select an airport code. Results cover departures during January–June of the selected Network year.');
val(airport,'B12','From');val(airport,'D12','PHX');airport.getRange('D12').format.fill='#FFF0D7';airport.getRange('D12').dataValidation={rule:{type:'list',formula1:"'Read me'!$A$22:$A$"+(21+data.airports.length)}};formula(airport,'F12',`="Year: "&${year}`);
const aExtra=[['origin',"'Airport'!$D$12"]];
for(const [r,label,f] of [[16,'Scheduled flights','scheduled_flights'],[18,'Arrivals with a recorded delay','eligible_arrivals'],[20,'Delayed arrivals (15+ min)','delayed_flights'],[22,'Cancelled flights','cancelled_flights']]){block(airport,`B${r}:E${r}`,label);formula(airport,`F${r}`,'='+sum('Airport data',f,aExtra));airport.getRange(`F${r}`).setNumberFormat('#,##0');}
val(airport,'B25','Delay rate');percent(airport,'F25','F20','F18');val(airport,'B27','Cancellation rate');percent(airport,'F27','F22','F16');
airport.getRange('I15:M15').values=[['Month','Eligible','Delayed','Airport','Network']];for(let m=1;m<=6;m++){const r=15+m;val(airport,`I${r}`,['Jan','Feb','Mar','Apr','May','Jun'][m-1]);formula(airport,`J${r}`,'='+sum('Airport data','eligible_arrivals',[...aExtra,['month',String(m)]]));formula(airport,`K${r}`,'='+sum('Airport data','delayed_flights',[...aExtra,['month',String(m)]]));percent(airport,`L${r}`,`K${r}`,`J${r}`);formula(airport,`M${r}`,`='Network'!F${23+m}`);}chart(airport,'line',['I15:I21','L15:L21','M15:M21'],'Airport and network delay rate','H24','P41');block(airport,'B31:F34','Use the counts to judge sample size. A small airport can move sharply with only a few delayed flights.',11,C.muted);airport.getRange('B31:F34').format.wrapText=true;
// Actual carrier names and formula-driven rates, not unweighted monthly averages.
const airlines=sheets.Airlines;shell(airlines,'Airline comparison','Reporting carriers. Differences reflect route mix as well as operating performance. January–June.');formula(airlines,'B12',`="Selected year: "&${year}`);
airlines.getRange('B15:G15').values=[['DOT ID','Airline','Scheduled','Eligible','Delayed','Delay rate']];data.carriers.forEach((r,i)=>{const n=16+i;val(airlines,`B${n}`,r.airline_key);val(airlines,`C${n}`,r.carrier_name);for(const [c,f] of [['D','scheduled_flights'],['E','eligible_arrivals'],['F','delayed_flights']])formula(airlines,`${c}${n}`,'='+sum('Airline data',f,[['airline_key',`$B${n}`]]));percent(airlines,`G${n}`,`F${n}`,`E${n}`);});airlines.getRange('C15:C35').format.columnWidthPx=205;airlines.getRange('D16:F35').setNumberFormat('#,##0');airlines.getRange('G16:G'+(15+data.carriers.length)).conditionalFormats.add('dataBar',{color:C.blue});airlines.getRange('B15:G15').format={fill:C.navy,font:{color:C.white,bold:true},wrapText:true,rowHeight:30};block(airlines,'I16:N22','Read this comparison carefully\n\nRegional carriers operate different networks from mainline carriers. These rates describe observed flights; they do not isolate airline quality.',11,C.muted);airlines.getRange('I16:N22').format.wrapText=true;
// Hourly timing exposes the daypart shape and selected-year cause mix.
const delays=sheets['Delay patterns'];shell(delays,'When delays build up','Scheduled local departure hour. Late arrival means 15+ minutes. January–June of the selected year.');formula(delays,'B12',`="Selected year: "&${year}`);
delays.getRange('B15:E15').values=[['Hour','Eligible arrivals','Delayed arrivals','Delay rate']];for(let h=0;h<24;h++){const r=16+h;val(delays,`B${r}`,`${String(h).padStart(2,'0')}:00`);formula(delays,`C${r}`,'='+sum('Hour data','eligible_arrivals',[['departure_hour',String(h)]]));formula(delays,`D${r}`,'='+sum('Hour data','delayed_flights',[['departure_hour',String(h)]]));percent(delays,`E${r}`,`D${r}`,`C${r}`);}delays.getRange('C16:D39').setNumberFormat('#,##0');chart(delays,'line',['B15:B39','E15:E39'],'Delay rate by scheduled departure hour','G15','P30');
delays.getRange('H33:J33').values=[['Reported cause','Minutes','Share']];const causes=[['Late aircraft','late_aircraft_minutes'],['Carrier','carrier_minutes'],['Airspace system','nas_minutes'],['Weather','weather_minutes'],['Security','security_minutes']];causes.forEach(([label,f],i)=>{const r=34+i;val(delays,`H${r}`,label);formula(delays,`I${r}`,'='+sum('Monthly data',f));percent(delays,`J${r}`,`I${r}`,'SUM($I$34:$I$38)');});delays.getRange('H33:H38').format.columnWidthPx=130;delays.getRange('I34:I38').setNumberFormat('#,##0');block(delays,'G42:O44','Cause shares describe reported delay minutes on delayed flights. The weather category alone does not capture every weather-related disruption.',10,C.muted);delays.getRange('G42:O44').format.wrapText=true;
// Audit values originate in independently executed SQL. Workbook checks also test its own source totals.
const audit=sheets['Data audit'];shell(audit,'Data checks and reconciliation','Measured results from the rebuild. Two flights lack arrival-delay values and are excluded from arrival rates.');
const checks=data.tests.map(t=>[t.check,t.actual,t.expected]);table(audit,[13,2],checks,['Check','Measured','Expected'],'PipelineChecks');audit.getRange('B13:B42').format.columnWidthPx=340;audit.getRange('C14:D42').setNumberFormat('#,##0');val(audit,'E13','Difference');for(let i=0;i<checks.length;i++)formula(audit,`E${14+i}`,`=C${14+i}-D${14+i}`);audit.getRange('E14:E'+(13+checks.length)).conditionalFormats.add('cellIs',{operator:'notEqual',formula:0,format:{fill:'#FCE4E4',font:{color:'#A31C2F',bold:true}}});val(audit,'H14','Workbook monthly flight count');formula(audit,'L14',`=SUM(${rangeMap['Monthly data'].scheduled_flights})`);val(audit,'H17','Independent flight-level row count');val(audit,'L17',data.profile.fact_rows);val(audit,'H20','Difference');formula(audit,'L20','=L14-L17');
const read=sheets['Read me'];read.showGridLines=false;read.getRange('A1:H'+(22+data.airports.length)).format={font:{name:'Arial',size:11,color:C.ink},columnWidth:22,rowHeight:22};read.tabColor=C.muted;
const notes=[['FLIGHTPATH','Data and methodology'],['Source','https://www.transtats.bts.gov/Fields.asp?gnoyr_VQ=FGJ'],['Coverage','24,416,952 reporting-carrier scheduled flights, Jan 2023–Jun 2026.'],['Comparison period','Reader views compare January–June in each selected year. Monthly data contains all 42 months.'],['Arrival denominator','Non-cancelled, non-diverted flights with recorded arrival-delay minutes.'],['On time','Arrival delay <15 minutes. Early arrivals count as on time.'],['Cancelled','Cancelled scheduled flights / all scheduled flights.'],['Severe delay','Arrival delay >=60 minutes / eligible arrivals.'],['Local time','Departure hour uses scheduled local time at the origin. 2400 is normalized to 00:00.'],['Reported causes','Minutes attributed to carrier, weather, NAS, security or late aircraft. Not counts of flights.'],['Scope','BTS reporting-carrier domestic operations; this is not every aircraft movement in U.S. airspace.'],['Refresh','Run scripts/refresh.py and scripts/build_excel.mjs to regenerate the workbook.'],['Power Query','A separate .pq import is included. It has not been executed inside Excel.'],['Native verification','Formula recalculation and exports were checked with Artifact Tool; Microsoft Excel was unavailable.'],['Use','Edit amber controls. Use the sheet tabs to navigate. Source tables remain inspectable.'],['Geography','OurAirports via datasets/airport-codes. Historical PBI coordinates retain the period code.'],['Built','2026-09-07']];read.getRange('A1:B17').values=notes;read.getRange('B1:B17').format.columnWidthPx=980;read.getRange('A1:A17').format.font={bold:true};read.getRange('A21:D21').values=[['Airport code','Airport name','City','State']];read.getRange('A22:D'+(21+data.airports.length)).values=data.airports.map(r=>[r.airport_code,r.airport_name,r.city_name,r.state_code]);read.freezePanes.freezeRows(21);
// Final layout and number formats after all data and column widths are present.
airport.getRange('J16:K21').setNumberFormat('#,##0');airport.getRange('L16:M21').setNumberFormat('0.0%');
for(const [s,r] of [[airport,'I15:M15'],[delays,'B15:E15'],[delays,'H33:J33']])s.getRange(r).format={fill:C.navy,font:{color:C.white,bold:true},wrapText:true,rowHeight:34};
net.getRange('B17:P18').format.horizontalAlignment='left';
audit.getRange('C13:D42').format.columnWidthPx=112;audit.getRange('L14:L20').setNumberFormat('#,##0');
for(const r of ['B2:P2','B4:P5','B7:P7','B9:P9'])audit.unmergeCells(r);
block(audit,'B2:P2','FLIGHTPATH   /   U.S. AIRLINE OPERATIONS',11,C.muted);block(audit,'B4:P5','Data checks and reconciliation',24,C.white,C.navy);block(audit,'B7:P7','Measured rebuild checks. Two missing arrival delays are excluded from arrival rates.',11,C.muted);block(audit,'B9:P9','USE THE SHEET TABS:  Network    Airport    Airlines    Delay patterns    Data audit',10,C.blue);
// Verify the input actually recalculates the same formulas, then restore it.
wb.recalculate();const tests=[];for(const y of [2023,2025,2026]){val(net,'D12',y);wb.recalculate();const expected=data.monthly.filter(r=>r.year==y&&r.month<=6).reduce((a,r)=>a+r.scheduled_flights,0);const actual=net.getRange('B17').values[0][0];if(Math.abs(Number(actual)-expected)>0)throw Error(`Year ${y}: ${actual} != ${expected}`);tests.push({year:y,expected,actual});}
val(net,'D12',2026);wb.recalculate();
const inspection=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|not implemented',options:{useRegex:true,maxResults:100},summary:'Formula errors'});await fs.writeFile(path.join(ROOT,'docs/evidence/excel/formula-scan.json'),inspection.ndjson);console.log(inspection.ndjson);
for(const name of names){const range=['Monthly data','Airport data','Airline data','Hour data'].includes(name)?'A1:M13':name==='Read me'?'A1:D17':name==='Data audit'?'A1:P42':'A1:P45';const preview=await wb.render({sheetName:name,range,scale:1,format:'png'});await fs.writeFile(path.join(ROOT,'docs/evidence/excel',name.replaceAll(' ','_')+'.png'),new Uint8Array(await preview.arrayBuffer()));}
await fs.writeFile(path.join(ROOT,'docs/evidence/excel/selector-checks.json'),JSON.stringify(tests,null,2));
const xlsx=await SpreadsheetFile.exportXlsx(wb);await xlsx.save(path.join(out,'Flightpath.xlsx'));console.log('Built Flightpath.xlsx');
